name: CI
on: [push, pull_request]
jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      jsOrTs: ${{ steps.filter.outputs.jsOrTs }}
      package: ${{ steps.filter.outputs.package }}
      test: ${{ steps.filter.outputs.test }}
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2.2.0
        id: filter
        with:
          filters: |
            jsOrTs:
              - '**/*.js'
              - '**/*.ts'
            package:
              - 'api-extractor.json'
              - 'composite-service.api.md'
              - 'package.json'
              - 'tsdx.config.js'
              - 'tsconfig.json'
              - 'yarn.lock'
              - 'src/**/*'
            test:
              - 'test/**/*'
      - run: echo Changes - jsOrTs=${{ steps.filter.outputs.jsOrTs }} package=${{ steps.filter.outputs.package }} test=${{ steps.filter.outputs.test }}
  lint:
    needs: [changes]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' || needs.changes.outputs.jsOrTs == 'true'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: actions/cache@v1
        with:
          path: node_modules
          key: nodeModules-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            nodeModules-
      - run: yarn install --frozen-lockfile
      - run: yarn lint
  build:
    needs: [changes]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' || needs.changes.outputs.package == 'true' || needs.changes.outputs.test == 'true'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: actions/cache@v1
        with:
          path: node_modules
          key: nodeModules-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            nodeModules-
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/
  check-api:
    needs: [changes, build]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' || needs.changes.outputs.package == 'true'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: actions/cache@v1
        with:
          path: node_modules
          key: nodeModules-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            nodeModules-
      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist/
      - run: yarn check-api
  test:
    needs: [changes, build]
    runs-on: ${{ matrix.os }}
    if: github.ref == 'refs/heads/master' || needs.changes.outputs.package == 'true' || needs.changes.outputs.test == 'true'
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04]
        node: [10, 12, 14]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: node_modules
          key: matrix-nodeModules-${{ matrix.os }}-${{ matrix.node }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            matrix-nodeModules-
      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist/
      - run: yarn install --frozen-lockfile
      - run: yarn test-only
  release:
    needs: [lint, build, check-api, test]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: actions/cache@v1
        with:
          path: node_modules
          key: nodeModules-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            nodeModules-
      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist/
      - run: yarn semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  website:
    needs: [release]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'refs/heads/master'
      - uses: actions/setup-node@v1
      - uses: actions/cache@v1
        with:
          path: node_modules
          key: nodeModules-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            nodeModules-
      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist/
      - run: yarn document-api
      - run: cd website && yarn && yarn build
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/build
